; Generated by FEARlabs Prog8 GameLinker from gameLink_template.p8

gameLink {

    ; this is set of main program data+subs that you would like 
    ; to be accessable from the blob

    const ubyte                 someNumbers_size    = 14
    &ubyte[someNumbers_size]    someNumbers         = $825
    
    extsub $85c                      = printNumber(ubyte n @ A) clobbers(A,X,Y)

}
